name: tcc_deficiencia
description: TCC Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_vision: ^1.1.4
  camera: ^0.10.5+5
  permission_handler: ^11.3.1
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_icons:
  image_path: "assets/icon/icon.jpg"
  adaptive_icon_foreground: "assets/icon/icon.jpg"
  adaptive_icon_background: "#ffffff"
  android: true
  ios: true

flutter:
  assets:
    - assets/
  uses-material-design: true
